**Проверить: код, дуальный коду Хэмминга - симплекс**  
Его параметры: (7, 3)

In [5]:
import numpy as np
import itertools

# H for Hamming (7,4) code
H = np.array([
    [1, 0, 1, 0, 1, 0, 1],
    [0, 1, 1, 0, 0, 1, 1],
    [0, 0, 0, 1, 1, 1, 1]
])

print(f"Generator matrix of dual code G_dual = H:\n{H}\n")
# Generate all codewords
weights = []
for info in itertools.product([0, 1], repeat=3):
    # с = m * G_dual
    codeword = (np.array(info) @ H) % 2
    weight = np.sum(codeword)
    weights.append(weight)
    print(f"{np.array(info)} -> {codeword} (weight: {weight})")

# Check nonzero weights
nonzero_weights = [w for w in weights if w > 0]

# Verify all nonzero weights are equal (simplex code property)
if len(set(nonzero_weights)) == 1:
    w = nonzero_weights[0]
    print(f"\nAll {len(nonzero_weights)} nonzero codewords have weight {w}")
    print(f"Minimum distance d_min = {w} = 2^(3-1) = 4, dual of Hamming (7,4) code is simplex (7,3) code")
else:
    print("\nNot a simplex code")

Generator matrix of dual code G_dual = H:
[[1 0 1 0 1 0 1]
 [0 1 1 0 0 1 1]
 [0 0 0 1 1 1 1]]

[0 0 0] -> [0 0 0 0 0 0 0] (weight: 0)
[0 0 1] -> [0 0 0 1 1 1 1] (weight: 4)
[0 1 0] -> [0 1 1 0 0 1 1] (weight: 4)
[0 1 1] -> [0 1 1 1 1 0 0] (weight: 4)
[1 0 0] -> [1 0 1 0 1 0 1] (weight: 4)
[1 0 1] -> [1 0 1 1 0 1 0] (weight: 4)
[1 1 0] -> [1 1 0 0 1 1 0] (weight: 4)
[1 1 1] -> [1 1 0 1 0 0 1] (weight: 4)

All 7 nonzero codewords have weight 4
Minimum distance d_min = 4 = 2^(3-1) = 4, dual of Hamming (7,4) code is simplex (7,3) code
