По минимальным многочленам $M_1(x)$ и $M_3(x)$ построить порождающий полином $g(x)$, порождающую матрицу $G$ и проверить, что $G * H^T = 0$

In [3]:
import numpy as np
from itertools import product

M1 = np.array([1, 1, 0, 0, 1], dtype=int)  # x^4 + x + 1
M3 = np.array([1, 1, 1, 1, 1], dtype=int)  # x^4 + x^3 + x^2 + x + 1

def poly_mul(p1, p2):
    res = np.zeros(len(p1) + len(p2) - 1, dtype=int)
    for i in range(len(p1)):
        if p1[i]:
            for j in range(len(p2)):
                if p2[j]:
                    res[i+j] ^= 1
    return res

# Порождающий полином g(x) = M1(x) * M3(x)
g = poly_mul(M1, M3)
n = 15
k = 15 - len(g) + 1

print(f"Порождающий полином g(x): {g}")

G = np.zeros((k, n), dtype=int)
for i in range(k):
    G[i, i:i+len(g)] = g

print(f"\nПорождающая матрица G ({k}x{n}):")
print(G)

def poly_div(dividend, divisor):
    dividend = dividend.copy()
    quotient = np.zeros(len(dividend) - len(divisor) + 1, dtype=int)
    for i in range(len(quotient)):
        if dividend[i]:
            quotient[i] = 1
            for j in range(len(divisor)):
                if divisor[j]:
                    dividend[i+j] ^= 1
    remainder = dividend[-(len(divisor)-1):] if len(divisor) > 1 else np.array([0])
    return quotient, remainder

x15_plus_1 = np.zeros(16, dtype=int)
x15_plus_1[0] = 1
x15_plus_1[15] = 1

h, rem = poly_div(x15_plus_1, g)
print(f"\nПроверочный полином h(x): {h}")

# Проверочная матрица H ((n-k) x n) из коэффициентов h(x) в обратном порядке
H = np.zeros((n-k, n), dtype=int)
h_rev = h[::-1]
for i in range(n-k):
    H[i, i:i+len(h_rev)] = h_rev

print(f"\nПроверочная матрица H ({n-k}x{n}):")
print(H)

# Проверка: G * H^T = 0
product = (G @ H.T) % 2
print(f"\nПроизведение равно нулю? - {np.all(product == 0)}")

Порождающий полином g(x): [1 0 0 0 1 0 1 1 1]

Порождающая матрица G (7x15):
[[1 0 0 0 1 0 1 1 1 0 0 0 0 0 0]
 [0 1 0 0 0 1 0 1 1 1 0 0 0 0 0]
 [0 0 1 0 0 0 1 0 1 1 1 0 0 0 0]
 [0 0 0 1 0 0 0 1 0 1 1 1 0 0 0]
 [0 0 0 0 1 0 0 0 1 0 1 1 1 0 0]
 [0 0 0 0 0 1 0 0 0 1 0 1 1 1 0]
 [0 0 0 0 0 0 1 0 0 0 1 0 1 1 1]]

Проверочный полином h(x): [1 0 0 0 1 0 1 1]

Проверочная матрица H (8x15):
[[1 1 0 1 0 0 0 1 0 0 0 0 0 0 0]
 [0 1 1 0 1 0 0 0 1 0 0 0 0 0 0]
 [0 0 1 1 0 1 0 0 0 1 0 0 0 0 0]
 [0 0 0 1 1 0 1 0 0 0 1 0 0 0 0]
 [0 0 0 0 1 1 0 1 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 1 0 1 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 1 0 1 0 0 0 1 0]
 [0 0 0 0 0 0 0 1 1 0 1 0 0 0 1]]

Произведение равно нулю? - True
